service: invoice-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DYNAMODB_TABLE: invoices
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:us-east-1:*:table/invoices"

functions:
  create:
    handler: invoices/create.create
    events:
      - http:
          path: invoices
          method: post
          cors: true

  list:
    handler: invoices/list.list
    events:
      - http:
          path: invoices
          method: get
          cors: true

  get:
    handler: invoices/get.get
    events:
      - http:
          path: invoices/{id}
          method: get
          cors: true

  update:
    handler: invoices/update.update
    events:
      - http:
          path: invoices/{id}
          method: put
          cors: true

  delete:
    handler: invoices/delete.delete
    events:
      - http:
          path: invoices/{id}
          method: delete
          cors: true

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}



#resources:
  # Resources:
  #   DynamoDbTable:
  #     Type: 'AWS::DynamoDB::Table'
  #     DeletionPolicy: Retain
  #     Properties:
  #       AttributeDefinitions:
  #         -
  #           AttributeName: id
  #           AttributeType: S
  #         -
  #           AttributeName: invoiceNumber
  #           AttributeType: S
  #       KeySchema:
  #         -
  #           AttributeName: id
  #           KeyType: HASH
  #       ProvisionedThroughput:
  #         ReadCapacityUnits: 1
  #         WriteCapacityUnits: 1
  #       TableName: ${self:provider.environment.DYNAMODB_TABLE}
  #       GlobalSecondaryIndexes:
  #         -
  #           IndexName: InvoiceNumberIndex
  #           KeySchema:
  #             -
  #               AttributeName: invoiceNumber
  #               KeyType: HASH
  #           Projection:
  #             ProjectionType: ALL
